version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - globomantics.identityserver
    ports:
      # we also want to refer to the same port,
      # both inside compose and from the host
      # the nginx port to listen has to match this port
      - "44395:44395"
    networks:
      # make host names available inside the globonet network
      # add aliases for this service that other services can use
      # to get here to this reverse proxy from within docker compose
      globonet:
        aliases: 
          - "id-local.globomantics.com"
          - "www-local.globomantics.com"

  globomantics.identityserver:
    image: ${DOCKER_REGISTRY-}globomanticsidentityserver
    build:
      context: .
      dockerfile: Globomantics.IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    # add to network
    networks:
      - globonet

  globomantics.ui:
    build:
      context: .
      dockerfile: Globomantics.Core/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
    ports:
      - "5005:5005"
    # add to network
    networks:
      - globonet

  globoseq:
    image: datalust/seq
    restart: unless-stopped
    ports:
        - "5342:80"
    environment:
        - ACCEPT_EULA=Y
    # add to network
    networks:
      - globonet


  globosmtp:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "5010:80"
    # add to network
    networks:
      - globonet

# declare network:
networks:
  globonet: {}