apiVersion: apps/v1
kind: Deployment
metadata:
  name: globoseq-app
spec:
  selector:
    matchLabels:
      app: globoseq-app
  replicas: 1
  template:
    metadata:
      labels:
        app: globoseq-app
    spec:      
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 5341
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"        
---
apiVersion: v1
kind: Service
metadata:
  name: globoseq-service
spec:
  selector:
    app: globoseq-app  
  type: NodePort  
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 31534

# service will be available on http://localhost:31534
# if no node port is specified, some will get auto assinged

---
apiVersion: v1
kind: Service
metadata:
  name: globoseq
spec:
  clusterIP: None # headless service
  selector:
    app: globoseq-app
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341

# we don't need to write log outside the cluster
# so this is a headless service
